### ISSUE TITLE
Problem with genre selection

### ISSUE THREAD

**Issue by MrG3cko** [AarushX/Epidemic#3]
Genres and subgenres that include spaces return problems.
for how I use the program I took the liberty of modifying the code in the following way
(line 61) & (line 71)
`
  command, *breadth = typed.split()
`
`
  genre_mod = ""
`
`
  for x in breadth:
`
`
      genre_mod = f"{genre_mod} {x}"
`
`
  genre_mod = genre_mod[1:]
`
`
[...]
`
`
    case "genre" | "genr" | "gen" | "g":
`
`
        if (genre_mod in GENRES) | (genre_mod in SUBGENRES):
`
`
          genres.append(urllib.parse.quote_plus(genre_mod))
`

**Comment by AarushX** [comment]
Hi MrG3cko, thank you for taking the effort to help this project out! for the moment however, I don't have any time to make any changes, but please let me know if you'd like to contribute any more to the project!

(when i get time, if you haven't already, i'll add this code-- it would def help out)

**Comment by AarushX** [comment]
Alright, I'm back, about to begin work on a lot of projects but I'll get this implemented ASAP.
